package statistics;

import java.util.ArrayList;
import java.util.List;

/*******
 * <p> Title: GradingExport Class </p>
 *
 * <p> Description: The Grading Audit &amp; Export serializer (TP3 Aspect #8). Given the list of
 * per-student records produced by the Aggregate Statistics Engine (statistics.ParticipationStats,
 * Aspect #4), it renders a single self-contained report that a grader can save and use to record
 * discussion-participation grades. The report has three parts in one file: an audit header
 * stating exactly what rule was checked and when, a comma-separated block that drops straight into
 * a gradebook, and a per-student audit detail showing the numeric comparison behind every verdict.
 * Together these satisfy the two halves of Aspect #8: the machine-readable compliance result for
 * recording grades, and a record of what the system checked. </p>
 *
 * <p> Like the engine it consumes, this class is a pure function of its inputs. buildReport takes
 * the records, the threshold, the viewer's name, and a timestamp, and returns a String; it never
 * reads the clock, opens a file, or touches a database. Keeping the clock and the file system out
 * of the serializer is deliberate: it is what lets the whole report be verified against an exact
 * expected String in the test suite, with no dependence on when or where the test runs. The
 * controller (guiStatistics.ControllerStatistics) is responsible for supplying the real timestamp
 * and viewer and for writing the returned text to disk. </p>
 *
 * <p> All output is plain ASCII. The report is intended to be opened in a text editor or imported
 * into a spreadsheet, so no em dashes or other non-ASCII characters are emitted, which avoids any
 * encoding surprise on import. </p>
 *
 * <p> Copyright: Lynn Robert Carter © 2025 </p>
 *
 * @author Weiye (Richard) Zhang (TP3 Aspect #8: Grading Audit &amp; Export)
 *
 * @version 1.00	2026-07-25	Initial version
 */
public class GradingExport {

	/* A 60-character rule used to frame the header and footer sections of the report. */
	private static final String HEAVY_RULE =
		"============================================================";

	/* A 60-character rule used to separate the audit-detail section from the CSV block. */
	private static final String LIGHT_RULE =
		"------------------------------------------------------------";


	/*******
	 * <p> Method: GradingExport() </p>
	 *
	 * <p> Description: The default constructor. Not used directly, since every method on this
	 * class is static; present only for consistency with the other classes in this package. </p>
	 *
	 */
	public GradingExport() {
	}


	/*******
	 * <p> Method: buildReport(List stats, int threshold, String viewer, String timestamp) </p>
	 *
	 * <p> Description: Renders the complete Aspect #8 report as a single String. The records are
	 * sorted alphabetically by student here, inside the serializer, so the output is deterministic
	 * no matter what order the caller supplies. The header reports the totals (checked, met, not
	 * met), the CSV block lists one row per student, and the audit-detail block spells out the
	 * numeric comparison (distinct answered against the threshold) that produced each verdict. </p>
	 *
	 * @param stats     specifies the per-student records to export; the list is not modified
	 *
	 * @param threshold specifies the distinct-students requirement the verdicts were judged against
	 *
	 * @param viewer    specifies the username of the grader running the export, for the audit trail
	 *
	 * @param timestamp specifies the human-readable time the export was run, for the audit trail
	 *
	 * @return the full report text, ready to be written to a file
	 *
	 */
	public static String buildReport(List<StudentStat> stats, int threshold,
	                                 String viewer, String timestamp) {

		// Work on a sorted copy so the caller's list is left untouched and output is stable.
		List<StudentStat> ordered = new ArrayList<>(stats);
		ordered.sort((a, b) -> a.getStudent().compareTo(b.getStudent()));

		int total = ordered.size();
		int met   = 0;
		for (StudentStat s : ordered) if (s.meetsRequirement()) met++;
		int notMet = total - met;

		StringBuilder sb = new StringBuilder();

		// ---- Audit header: what was checked, by whom, when, and the totals ----
		sb.append(HEAVY_RULE).append("\n");
		sb.append("CSE 360 - Discussion Participation: Grading Audit & Export").append("\n");
		sb.append("TP3 Aspect #8 - Grading Audit & Export").append("\n");
		sb.append(HEAVY_RULE).append("\n");
		sb.append("Generated:        ").append(timestamp).append("\n");
		sb.append("Generated by:     ").append(viewer).append("\n");
		sb.append("Rule checked:     A student must answer questions from at least ")
		  .append(threshold).append(" distinct other students.").append("\n");
		sb.append("Threshold:        ").append(threshold).append(" distinct students").append("\n");
		sb.append("Students checked: ").append(total).append("\n");
		sb.append("Students MET:     ").append(met).append("\n");
		sb.append("Students NOT MET: ").append(notMet).append("\n");
		sb.append(HEAVY_RULE).append("\n");
		sb.append("\n");

		// ---- CSV block: machine-readable result for recording grades ----
		sb.append(csvHeader()).append("\n");
		for (StudentStat s : ordered) sb.append(csvRow(s)).append("\n");
		sb.append("\n");

		// ---- Audit detail: the numeric comparison behind each verdict ----
		sb.append(LIGHT_RULE).append("\n");
		sb.append("Audit detail - what the system checked, per student").append("\n");
		sb.append(LIGHT_RULE).append("\n");
		for (StudentStat s : ordered) sb.append(auditLine(s, threshold)).append("\n");

		// ---- Footer ----
		sb.append(HEAVY_RULE).append("\n");
		sb.append("End of report.").append("\n");
		sb.append(HEAVY_RULE).append("\n");

		return sb.toString();
	}


	/*******
	 * <p> Method: csvHeader() </p>
	 *
	 * <p> Description: Returns the fixed column header for the CSV block. Kept as its own method
	 * so the header and the rows can never drift out of sync and so it can be asserted directly
	 * in the test suite. </p>
	 *
	 * @return the comma-separated column header line
	 *
	 */
	public static String csvHeader() {
		return "student,posts,replies,distinctAnswered,verdict";
	}


	/*******
	 * <p> Method: csvRow(StudentStat s) </p>
	 *
	 * <p> Description: Renders one student's record as a single comma-separated row matching the
	 * order of csvHeader. The verdict is written as MET or NOT MET. Every field is passed through
	 * the csv escaper so that a value containing a comma or quote could never corrupt the column
	 * layout, even though canonical usernames never contain one. </p>
	 *
	 * @param s specifies the student record to render
	 *
	 * @return the comma-separated data row for the student
	 *
	 */
	public static String csvRow(StudentStat s) {
		return csv(s.getStudent()) + ","
		     + s.getPostsAuthored() + ","
		     + s.getRepliesAuthored() + ","
		     + s.getDistinctStudentsAnswered() + ","
		     + csv(verdictText(s));
	}


	/*******
	 * <p> Method: auditLine(StudentStat s, int threshold) </p>
	 *
	 * <p> Description: Renders one student's audit-detail line: the three tallies followed by the
	 * verdict and, in parentheses, the exact numeric comparison that produced it, for example
	 * "(3 &gt;= 3)" for a pass or "(1 &lt; 3)" for a failure. This is the "record of what the
	 * system checked" that a grader can inspect to confirm a verdict by hand. </p>
	 *
	 * @param s         specifies the student record to render
	 *
	 * @param threshold specifies the requirement the distinct count was compared against
	 *
	 * @return the fixed-width audit-detail line for the student
	 *
	 */
	public static String auditLine(StudentStat s, int threshold) {
		int distinct = s.getDistinctStudentsAnswered();
		String comparison = s.meetsRequirement()
			? "(" + distinct + " >= " + threshold + ")"
			: "(" + distinct + " < "  + threshold + ")";
		return String.format("%-16s posts=%-3d replies=%-3d distinctAnswered=%-3d  %-7s %s",
			s.getStudent(), s.getPostsAuthored(), s.getRepliesAuthored(),
			distinct, verdictText(s), comparison);
	}


	/*******
	 * <p> Method: verdictText(StudentStat s) </p>
	 *
	 * <p> Description: Maps a record's boolean compliance verdict to the text used everywhere in
	 * the report: "MET" when the requirement is satisfied, "NOT MET" when it is not. </p>
	 *
	 * @param s specifies the student record whose verdict is wanted
	 *
	 * @return "MET" if the student met the requirement, otherwise "NOT MET"
	 *
	 */
	public static String verdictText(StudentStat s) {
		return s.meetsRequirement() ? "MET" : "NOT MET";
	}


	/*******
	 * <p> Method: csv(String field) </p>
	 *
	 * <p> Description: Escapes a single field for safe inclusion in the CSV block following the
	 * common convention: a field containing a comma, a double quote, or a line break is wrapped
	 * in double quotes and any embedded double quote is doubled. Fields with none of these are
	 * returned unchanged. Canonical usernames never trigger escaping, but handling it keeps the
	 * export robust against any future identifier that does. </p>
	 *
	 * @param field specifies the raw field value to escape
	 *
	 * @return the field, quoted and escaped only if it needs to be
	 *
	 */
	private static String csv(String field) {
		if (field == null) return "";
		boolean mustQuote = field.contains(",") || field.contains("\"")
			|| field.contains("\n") || field.contains("\r");
		if (!mustQuote) return field;
		return "\"" + field.replace("\"", "\"\"") + "\"";
	}
}
